#!/bin/bash
# STOP! Before going any further, think: are you going to regret the decision
# to write this script?
#     Deciding to write this in bash was not one of my better decisions.
#     -- https://twitter.com/alex_gaynor/status/369892494114164736

IFS="`printf "\n\t"`"
set -eu
cd "$(dirname "$0")"

env="${1-}"
if [[ "$env" != "dev" && "$env" != "prod" ]]; then
    echo "USAGE: $0 [dev|prod]"
    echo "Builds and deploys cupsd into either 'dev' or 'prod'"
    exit 1
fi

repo="gcr.io/sx-ops-$env/ops-prometheus-cups_exporter"
tag="$(git rev-parse HEAD)"
if [[ ! -z "$(git status --porcelain)" ]]; then
    tag="$tag-dirty"
fi

if [[ ! -e "$HOME/.sx-bashrc" ]]; then
    echo "Error: $helm_cmd not found"
    echo "Hint: install the developer tools from: https://github.com/Sheertex/ops-developer/"
    exit 1
fi

shopt -s expand_aliases
. "$HOME/.sx-bashrc"
run_helm() {
    if [[ "$env" == "dev" ]]; then
        sx-dev-helm "${@}"
    elif [[ "$env" == "prod" ]]; then
        sx-prod-helm "${@}"
    else
        echo "Unexpected environment: $env"
    fi
}

set -x

./docker-build
docker tag sx-prometheus-cups_exporter "$repo:$tag"
docker push "$repo:$tag"
run_helm upgrade --install prometheus-cups-exporter \
    --set "image.tag=$tag" \
    --set "image.repository=$repo" \
    ./helm-chart/
