apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-cups-exporter.fullname" . }}
  labels:
    {{- include "prometheus-cups-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "prometheus-cups-exporter.selectorLabels" . | nindent 4 }}

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus-cups-exporter.fullname" . }}
  labels:
    {{- include "prometheus-cups-exporter.labels" . | nindent 4 }}
    prometheus: prom-prometheus
spec:
  selector:
    matchLabels:
      {{- include "prometheus-cups-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
  - interval: 30s
    path: /
    port: metrics
